version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "cargo"
    directory: "/cartographer"
    schedule:
      interval: "daily"
